### ISSUE TITLE
easy and automatic geocoding wanted

### ISSUE THREAD

**Issue by heikohaensge** [FriendsOfTYPO3/tt_address#237]
## Feature Request

**Is your feature request related to a problem? Please describe.**
At the moment geocoding has to be done manually or by CLI - both not really handy.

**Describe the solution you'd like**
It would be great if there would be an option to geocode addresses entered/edited automatically if a Google maps Key is provided in the extension options or typoscript setup. 
It would be great as well if there would be a backend module to invoke a mass geocoding if a Google maps Key is provided in the extension options. 
For inspirations please see extension wec_map we used extensively so far, but to have maps finally directly in tt_address is much more preferable. :-)

**Comment by BastianBalthasarBux** [comment]
Latest version of tt_address (see this repo) offers that already.

1. geocoding on each address is already there since a couple of versions, and it is done via nominatim (so no google involved, no map key necessary ...).
It is done right in the moment, when you click the map-wizard icon (with some prevention of too many geocoding-requests, just to not stress these free open service). There are several fallbacks (full address, city, country), and if geocoding totally fails, the fallback goes to Kopenhagen, Denmark as small a tribute and salute to Kaspar ... ;)

2. mass geocoding is also there, since march 2019 or so, you could do it from CLI or in TYPO3 Scheduler. But keep in mind, @georgringer realised it with googlemaps (not sure, why this must has been ... ;)), and it is done with a symfony command controller, which means, that task is only available for TYPO3 v9.5 and higher.

So in the end I would say: your feature requests are already implemented very well. ;)
If you feel, something is missing, just comment to that closed ticket, I will reopen if I feel it's appropriate
