### ISSUE TITLE
Problem with combined name field

### ISSUE THREAD

**Issue by SicorDev** [FriendsOfTYPO3/tt_address#27]
Hello,

as suggested, a repost on github:

We observed a little problem with the auto created "name" field:

Behaviour now: If you clear the other three name fields (first/middle/last) and save, then the "name" field stays filled with the previous content.

Should be: If you clear the other three name fields (first/middle/last) and save, then the "name" field should be cleared as well.

Can be tested with any address entry in the backend, with version 3.2.1.

**Comment by BastianBalthasarBux** [comment]
A short history of the combined name-field: A long time ago in a galaxy far, far away ... there was just this single field for names.
Not so long ago, but also many years already the decision was made to split it up to first, middle, last.
But the combined name field was kept for backwards compatibility, as automatically splitting up names isn't just a no-brainer.
That's why there is a setting in den extensions configuration in EM. "%1$s %3$s" is its default value, which basically means: firstname and lastname.
We can't clear the name, if both fields are empty while saving records, because if you did not split up your names yet, it will just delete your name, and the solely purpose of that field was **backwards compatibility**.
**The suggested proceeding is:** deactivate combined name field with the dedicated setting in the extensions configuration in EM, and remove the sprintf setting accordingly, if you do not need or use this combined name field!
We did not discuss this topic yet internally, but after having this field now since version 2.0.0, I am thinking about removing it completely in one of the next few releases anyway.

**Comment by BastianBalthasarBux** [comment]
I just rethought my findings accordingly, and I will vote for keeping the combined name field also for the future: It's easier for importing address-lists which do not have splitted up names too ...

BTW: you could remove the tick in 'readonly' in the extensions configuration, so you are at least able to clear this field manually.

**Comment by SicorDev** [comment]
Thank you very much for your analysis of this issue. I now fully understand the problem you're facing here and will just remove the write protection, which seems to be the best compromise currently.

With hindsight it probably would've been better if you had just kept the name field as is and only added first and middle name for splitting purposes I think ;-)

**Comment by BastianBalthasarBux** [comment]
The decision was made ages ago, I am not sure if Kaspar made it, or if the extension was back then already moved to Ingo.
But if they would have went the way you suggest, you would have a perfect mess then. You will get a field which maybe holds the whole name. Or maybe just the lastname.
Think of the frontend (e.g. sorting by lastname) ...
The solution is not absolutely perfect, but I think it is the best solution we could ever get. But for sure we are open for suggestions. If there will be a "god-like" solution someday, just drop as a line on github. ;)
For now I will close this issue.
Kind regards from Innsbruck
