### ISSUE TITLE
Brandnew installation of tt_address version 3.2.1 on a TYPO3 CMS version 8.5.1 gets blank result page

### ISSUE THREAD

**Issue by angeloprevitali** [FriendsOfTYPO3/tt_address#30]
If you install a brandnew TYPO3 CMS version 8.5.1 with the actual EXT_ttaddress version 3.2.1, which is marked as "stable" there are no results in FE and only a blank page. Is this version really TYPO3 version 8 compatible? I dubt it. Also a lot of labels of the fields in the BE in the list view are missing. 

Are there any plans concerning adapting and fixing this EXT:?

Thanks for feedback.

Regards,
Angelo

**Comment by BastianBalthasarBux** [comment]
Hi, yes the extension is currently refurbished.
Most labels in backend in Version 8 should now work.
We rely a lot on SYSEXT:lang and right now also on the gone SYSEXT:cms in case of the labels!
The last one has completely been removed in 8 and therefore we need to adjust things (locallang_ttc.xlf has been moved to SYSEXT:frontend).
The new version won't be compatible to TYPO3 6.2 because of this reason.

Concerning your 'blank page': Are you able to look into the error logs? A blank page very often means a php-error, which should be logged.

**Comment by sytura** [comment]
Hi,

same issue in my TYPO3 8.7.0 and tt_address 3.2.1 installation. The plugin is added to a page, but NOW output is shown by the plugin. I checked my configuration again and again. But it does not work with the default configuration , too. Complety no outpout!

Cheers

Roland

**Comment by andreasmerkel** [comment]
Hi,
we have the same issues with Typo3 8.7 and tt_address 3.2.1. After inserting the plugin, we've got a blank page, too. The Admin Panel says:  Class "tx_ttaddress_pi1" did not exist

Best,
Andreas

**Comment by andreasmerkel** [comment]
Hi again,
tt_address loads its pi1 classes in 'ext_localconf.php' through 'addPItoST43()'. This is no longer supported since Typo3 8.X. ([link to api](https://typo3.org/api/typo3cms/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_utility_1_1_extension_management_utility.html#ac5855624506bf76452e495738be90132))
As a **workaround**(!), I added the following line to the classmap in the autoloader section (in ext_emconf.php):
 10 => 'pi1'
So, every class in the directory 'pi1' is also loaded and the plugin works again...

Best, 
Andreas

**Comment by BastianBalthasarBux** [comment]
Thank you andreas. I will have a look at it.
Alternatively you could try out this one: https://github.com/BastianBalthasarBux/tt_address
without activating pi_base plugin, instead there are an extbase controller and fluid-templates in place. But please note: i did not test it on 8 yet, and as there is a lot of new code, consider it testing on a dev installation first!

**Comment by bmack** [comment]
Hey,

I fixed the issue in the master branch with this commit:
https://github.com/FriendsOfTYPO3/tt_address/commit/ae16447f4077b510e900667cd867fdb517cd5836

You need to go to the install tool and press the "Create autoload information for extension" button in the "Important actions" section, or via composer mode, just add "composer dumpautoload".

**Comment by bmack** [comment]
Can you confirm your issue is solved by that?

**Comment by andreasmerkel** [comment]
Hi,
yes, your fix works as expected. Thank you very much!
Best, Andreas
