### ISSUE TITLE
Security problem on show action

### ISSUE THREAD

**Issue by Guigue79** [FriendsOfTYPO3/tt_address#362]
## Bug Report
In version 5.2.1, there is no control to check if the tt_address record is in the list of allowed pages.
With this security flaw, we can for example display informations of user who is subscribed to the newsletter.

The setRespectStoragePage is disabled in addressrepository file

```
 /**
     * @param \FriendsOfTYPO3\TtAddress\Domain\Model\Address $address
     */
    public function showAction(\FriendsOfTYPO3\TtAddress\Domain\Model\Address $address = null)
    {
        if ($address === null) {
            $this->redirectToUri($this->uriBuilder->reset()->setTargetPageUid((int)$GLOBALS['TSFE']->id)->build());
        }
	else {
            $provider = GeneralUtility::makeInstance(AddressTitleProvider::class);
            $provider->setTitle($address, (array)($this->settings['seo']['pageTitle'] ?? []));
        }

        $this->view->assign('address', $address);

        CacheUtility::addCacheTagsByAddressRecords([$address]);
    }
```

**Comment by linawolf** [comment]
@Guigue79  if you think, you found a security related issue, please contact the Security Team! Don't discuss it here! https://typo3.org/community/teams/security/contact-us

**Comment by derhansen** [comment]
The TYPO3 Security Team decided, that this issue will not be handled as a security issue in the extension, because the described behavior is caused by Extbase persistence. The root cause of the problem can however not be fixed easily/without highly breaking behavior in Extbase, which will affect many extensions in the TYPO3 ecosystem. A Public Service Announcement describing possibilities to mitigate the issue will be published in may 2022. Additionally, a public PR with a fix for `tt_address` will be provided.
