### ISSUE TITLE
Sorting does not (fully) work for selection of single records

### ISSUE THREAD

**Issue by responseinformationsdesign** [FriendsOfTYPO3/tt_address#421]
TypoScript setting "plugin.tx_ttaddress.settings.sortBy" is totally ignored even if flexform value of settings.sortBy is set to default.

If flexform value of settings.sortBy is set to default records are displayed in the order they were added (something I would expect for flexform value "Manual sorting [sorting]).

**Comment by Hawkeye1909** [comment]
I just experienced the same thing. I think the TypoScript setting is ignored because the value of the "Default" option in the flexform is not empty (it's "default"). However, the TypoScript utility only overrides empty fields. So there either has to be an exception for the sortBy field or the value should be ""...

**Comment by georgringer** [comment]
so who wants to do a PR?

**Comment by georgringer** [comment]
fixed it. @Hawkeye1909 wanna do a test and afterwards I would do a release

**Comment by Hawkeye1909** [comment]
Tested it and it works here. If you do a release, could you please do one for v6 as well?
