### ISSUE TITLE
Store backwards compatibility name in name field broken

### ISSUE THREAD

**Issue by klodeckl** [FriendsOfTYPO3/tt_address#443]
Hello, the feature “Store backwards compatibility name in name field” does not work anymore (name field stays empty). It seems to be related to the TYPO3 update from 9 to 10. In TYPO3 9 and tt_address 5.3.0 it worked. After update to TYPO3 10 it doesn’t work anymore (no matter if tt_address version is 5.3.0 or 6.1.0). PHP 7.4.

**Comment by georgringer** [comment]
breaking change in 6.0, see https://github.com/FriendsOfTYPO3/tt_address/blob/master/Documentation/Administration/Changelog/v/6-0-0.rst#handling-of-field-name

**Comment by klodeckl** [comment]
What a pitty, direct_mail uses the field “name“ for viewing the recipients list in the recipients module. Why not remove the field “name“ completely?!

**Comment by klodeckl** [comment]
https://github.com/kartolo/direct_mail/issues/329

**Comment by georgringer** [comment]
didn't remove it to have the chance to either use a custom implementation and to be less breaking.

the address tries to follow semantic versioning, so the problem was more https://github.com/kartolo/direct_mail/commit/8f9234e0be42031f6852679231919e18e6834cbc to just allow the next major versions without checking the breaking changes
