### ISSUE TITLE
[FEATURE] Map zooming

### ISSUE THREAD

**Issue by morange** [FriendsOfTYPO3/tt_address#493]
## Feature Request

**Is your feature request related to a problem? Please describe.**
If you include the map in pages, scroll over it in the frontend and you happen to stop in the area of the map - then you can’t scroll on automatically. You always zoom in the map first.

**Describe the solution you'd like**
The map should not zoom automatically, but only with a click on + or - (top left).

**Comment by BastianBalthasarBux** [comment]
In general: This is an expected behaviour called "scrollWheelZoom".

Workaround: Zooming could be disabled with a custom javascript for leaflet integration and add just:
obj.map.scrollWheelZoom.disable();

Maybe we could add a setting to the flexform which allows to disable scrollWheelZoom by editors.

**Comment by georgringer** [comment]
please don't add more settings. It is ok to improve the JS but the default implementation is really simple and should stay like that.
