### ISSUE TITLE
Use translation.typo3.org for translations

### ISSUE THREAD

**Issue by sbusemann** [FriendsOfTYPO3/tt_address#61]
Added by Stefan Neufeind

moved from: https://forge.typo3.org/issues/59100

There are not too many translation-strings in the extension. But it would imho be a great step to use the central translation-server and download additional languages through the Language-module in TYPO3 etc.
http://translation.typo3.org/

Add existing translation-strings on the translation-server.

**Comment by xperseguers** [comment]
This is done already, cannot say since when but for a while now: https://translation.typo3.org/projects/TYPO3.ext.tt_address/

**Comment by sbusemann** [comment]
perfect, thanks for the feedback!

**Comment by neufeind** [comment]
There are some leftover German translations that need to be migrated to translations.typo3.org and then deleted in the repo. https://github.com/FriendsOfTYPO3/tt_address/tree/master/Resources/Private/Language
They don't exist on pootle yet. Xavier told me we'll have to wait until the next extension-release until pootle will pickup the new files from TER so that afterwards we can enter the translations.
I was granted the necessary rights on pootle already. So then I could take care of it.

Imho let's keep this issue open until we prepare for the next release and can finally resolve the translation-topic.

**Comment by georgringer** [comment]
translation server won't be supported, will add everything to extension until next solution comes up
